FROM node:18-alpine AS node_stage

WORKDIR /app/boilerplate-spring-boot-docker

COPY package.json package-lock.json ./

RUN npm i

FROM eclipse-temurin:21-jdk-alpine AS java_stage

RUN apk update && apk add --no-cache \
    curl \
    maven \
    git \
    nodejs \
    npm

RUN npm install -g npm@9.3.0

WORKDIR /app/boilerplate-spring-boot-docker

COPY . .

RUN mvn dependency:resolve

CMD ["sh"]
